// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-DisplayIO",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-DisplayIO", targets: ["AATKit-DisplayIO"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-DisplayIO",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATDIOSDK",
                    "AATDisplayIOAdapter",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-DisplayIO"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATDIOSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/DIOSDK.zip",
            checksum: "4d789a1b3e3ecab35f35450644528ffd5117eb57985486011faa6feebd0a6d76"
        ),
        .binaryTarget(
            name: "AATDisplayIOAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATDisplayIOAdapter.zip",
            checksum: "7d4cdf6deaaa840a5a8a185fdffe836342acc4b5f1bf2f7d074e42097fc3ec7b"
        ),
    ]
)
