// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-DisplayIO",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-DisplayIO", targets: ["AATKit-DisplayIO"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-DisplayIO",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATDIOSDK",
                    "AATDisplayIOAdapter",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-DisplayIO"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATDIOSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/DIOSDK.zip",
            checksum: "5e9891ce2e42992970982275e336d9614c7f541735bc7993abaff544a856578c"
        ),
        .binaryTarget(
            name: "AATDisplayIOAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATDisplayIOAdapter.zip",
            checksum: "ee32d7e2af4a9536052b4b0e1cdb06771a8d4d34567aed2dbde028c480d8672a"
        ),
    ]
)
